version: 2

project_name: helm-deep-pack

before:
  hooks:
    - go mod download

builds:
  - id: helm-deep-pack
    main: .
    binary: helm-deep-pack
    hooks:
      pre:
        - cmd: ./scripts/build-push-embed.sh
          env:
            - GOOS={{ .Os }}
            - GOARCH={{ .Arch }}
            - VERSION={{ .Version }}
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X helm-deep-pack/cmd.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: push-images
    main: ./cmd/pushimages
    binary: push_images
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X helm-deep-pack/cmd/pushimages.version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^Merge pull request"

release:
  prerelease: auto
